# This is a basic workflow to help you get started with Actions

name: Production Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID_PROD}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_PROD}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION_PROD}}
      REACT_APP_ENV: production
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: CI=false REACT_APP_ENV=production npm run build

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: build
          bucket: ${{secrets.AWS_S3_BUCKET_PROD}}
          dist-id: ${{secrets.DIST_ID_PROD}}
          invalidation: / *
